from_latest_tag = false
ignore_merge_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
tag_prefix = "v"
branch_whitelist = ["main", "release/*"]
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
  "cargo set-version {{version}}",
]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
"""

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
