ARG KUBIMO_MARIMO_IMAGE=ghcr.io/aqora-io/kubimo-marimo:0.1.14
FROM ${KUBIMO_MARIMO_IMAGE}

USER root
RUN uv pip install --system 'aqora-cli[pyarrow]>=0.24.0'

USER me
COPY --chown=me ./docker/kubimo/marimo /home/me/.config/marimo
