[project]
name = "use-case-aggto77gtj2fhndxvdkr66vav4"
version = "0.2.0"
requires-python = ">=3.7"

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.aqora]
data = "data"
