[completion]
activate_on_typing = true
copilot = false

[language_servers.ty]
enabled = true

[language_servers.basedpyright]

[language_servers.pylsp]
enable_pyflakes = false
enable_mypy = true
enabled = false
enable_pylint = false
enable_flake8 = false
enable_pydocstyle = false
enable_ruff = true

[save]
format_on_save = false
autosave = "after_delay"
autosave_delay = 1000

[runtime]
auto_reload = "off"
std_stream_max_bytes = 1000000
reactive_tests = true
watcher_on_save = "lazy"
output_max_bytes = 8000000
default_auto_download = ["html"]
on_cell_change = "autorun"
auto_instantiate = false
default_sql_output = "auto"
dotenv = [".env"]

[package_management]
manager = "uv"

[formatting]
line_length = 79

[diagnostics]
enabled = false

[ai]
rules = ""
mode = "manual"

[ai.models]
custom_models = []
displayed_models = []

[experimental]

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[display]
default_table_max_columns = 50
default_table_page_size = 10
cell_output = "below"
default_width = "full"
theme = "light"
code_editor_font_size = 14
dataframes = "rich"
reference_highlighting = false
custom_css = ["/home/me/.config/marimo/marimo.css"]

[server]
follow_symlink = false
browser = "default"

[snippets]
include_default_snippets = true
custom_paths = []
