name: "Build"

on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.target }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - run: pip install build maturin
      - run: python3 -m build -n
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.target }}-dist
          path: dist
