name: "Build and Check"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt --all --check
      - run: cargo clippy -- -D warnings
      - run: cargo build --release
